
server:
  port: 3344

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hudewu-cmd/springcloud-config.git
          search-paths:
            - springcloud-config
          force-pull: true
          username: 710414646@qq.com
          password: hu111de093wu
      label: master



  application:
    name: cloud-config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
