server:
  port: 9527
spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      routes:
         - id: payment-route
#           uri: http://localhost:8001
           uri: lb://cloud-payment-service
           predicates:
             - Path=/payment/get/** # 断言，路径相匹配的进行路由
             - After=2021-03-29T14:16:16.463+08:00[Asia/Shanghai]
           fiters:
             - AddRequestHeader=X-Request-red, blue
         - id: payment-route2
#           uri: http://localhost:8001
           uri: lb://cloud-payment-service
           predicates:
               - Path=/payment/lb/** # 断言，路径相匹配的进行路由
               - After=2021-03-29T14:16:16.463+08:00[Asia/Shanghai]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群
      defaultZone: http://localhost:7001/eureka #单机
